---
title: "NE WNV Example"
author: "Kelly Smith & Drew Tyre"
date: "`r Sys.Date()`"
output: html_document
vignette: >
  %\VignetteIndexEntry{Functional Linear Modeling for Vector-borne Disease}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up data for example
```{r data, message=FALSE}
library(tidyverse)
library(flm) # makes it easier to do quality control to have functions readily available
#**# Moving code from assembleData_lags file

# Read in population data
pop = flm::NE_county_pops
# pop <- read.csv("data/NE_county_pops.csv", stringsAsFactors = FALSE)

#Human cases. In this example, cases is the rounded value of the fitted model (i.e. simulated)
cases = flm::sampledat
# cases <- read.csv("data/sampledat.csv", stringsAsFactors = FALSE)

# Read in environmental data
NEdat = flm::NEdat
# NEdat <- read.csv("data/NEdat.csv", stringsAsFactors = FALSE)

# Read in spi
spi = flm::spi
# spi <- read.csv("data/NEco_spi1_2019-12-15.csv", stringsAsFactors = FALSE)

# Read in spei
spei = flm::spei
# spei <- read.csv("data/NEco_spei1_2019-12-15.csv", stringsAsFactors = FALSE)

# Specify the last date to use
target.date = "2018-02-01"

# Specify the first year of data to use
start.year = 2002

# Specify where to put the results
#results.path = paste0(tempdir(), "/")

```
## Some basic quality control on synthetic data

Our approach struggles if there are counties with no cases.

```{r}
data <- assemble.data.lags(pop, cases, NEdat, spi, spei, target.date = "2018-02-02", start.year = 2004,
                           in.seed = 4872957)
allLagsT <- data[[1]] # 2004 - 2017
# how many counties lack cases?
allLagsT %>% group_by(County) %>% 
  summarize(total_cases = sum(cases)) %>% 
  count(total_cases>0)

```

What does the state total look like plotted 
against time?

```{r}
allLagsT %>% group_by(year) %>% 
  summarize(total_cases = sum(cases)) %>% 
  ggplot() + 
  geom_point(mapping = aes(x = year, y = total_cases))
```



## Run the model


```{r flm}

#**# Turned off function call while checking that the package loads
flm.results = flm::call.flm(pop, cases, NEdat, spi, spei, target.date, start.year, in.seed = 4872957)

# Examine flm.results
#list.files(results.path)
```
